Description: This is the Stack Description
Resources:
  lambdaRoleC844FDB1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      Description: Lambda role for ts-lambda
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/ReadOnlyAccess
      RoleName: ts-lambda-lambda-role-develop
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/lambdaRole/Resource
  lambdaExecutionAccess82ECF6E2:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: lambdaExecutionAccess
      Roles:
        - Ref: lambdaRoleC844FDB1
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/lambdaExecutionAccess/Resource
  lambdaSG81E771DE:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ts-lambda-stack-develop/lambdaSG
      GroupName: ts-lambda-lambda-security-group-develop
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        - CidrIp: 10.3.0.0/16
          Description: Allow internal VPC traffic
          FromPort: 0
          IpProtocol: tcp
          ToPort: 65535
      VpcId: vpc-009efe79ac997c618
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/lambdaSG/Resource
  lambdaLayer857D4AF4:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket: cdk-hnb659fds-assets-612659717478-ap-southeast-2
        S3Key: 5947d7a0930311fd47fce02ef60bb06e6dbd1f3dc3c89b1903215a7a66115127.zip
      CompatibleRuntimes:
        - nodejs14.x
      Description: Lambda Layer for ts-lambda
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/lambdaLayer/Resource
      aws:asset:path: /Users/prasaddomala/GitRepos/kheriox/youtube/yt-typescript-lambda-cdk/lambda-layer
      aws:asset:is-bundled: false
      aws:asset:property: Content
  publicfunctionfunction65B26B99:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-612659717478-ap-southeast-2
        S3Key: 6524c803778d6198de0d33beb43a5d9d948c0bdcb8e6209746f313c24c5d075a.zip
      Role:
        Fn::GetAtt:
          - lambdaRoleC844FDB1
          - Arn
      Environment:
        Variables:
          REGION: ap-southeast-2
          ENV: develop
          GIT_BRANCH: develop
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      FunctionName: ts-lambda-public-function-develop
      Handler: index.handler
      Layers:
        - Ref: lambdaLayer857D4AF4
      MemorySize: 1024
      Runtime: nodejs14.x
      Timeout: 900
    DependsOn:
      - lambdaRoleC844FDB1
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/public-function-function/Resource
      aws:asset:path: /Users/prasaddomala/GitRepos/kheriox/youtube/yt-typescript-lambda-cdk/cdk.out/asset.6524c803778d6198de0d33beb43a5d9d948c0bdcb8e6209746f313c24c5d075a
      aws:asset:is-bundled: true
      aws:asset:property: Code
  fnpublicfunctionloggroupA0A81846:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/ts-lambda-public-function-develop
      RetentionInDays: 30
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/fn-public-function-log-group/Resource
  privatefunctionfunctionB21CF630:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-612659717478-ap-southeast-2
        S3Key: c993b10b13f96d4647db0cf6a9a7019710b34f61600695d887ad66e144f8a93c.zip
      Role:
        Fn::GetAtt:
          - lambdaRoleC844FDB1
          - Arn
      Environment:
        Variables:
          REGION: ap-southeast-2
          ENV: develop
          GIT_BRANCH: develop
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      FunctionName: ts-lambda-private-function-develop
      Handler: index.handler
      Layers:
        - Ref: lambdaLayer857D4AF4
      MemorySize: 2048
      Runtime: nodejs14.x
      Timeout: 300
      VpcConfig:
        SecurityGroupIds:
          - Fn::GetAtt:
              - lambdaSG81E771DE
              - GroupId
        SubnetIds:
          - subnet-029d25ea0d0b6a906
          - subnet-08b53dda246384b1f
          - subnet-01a855a9fe96b9ded
    DependsOn:
      - lambdaRoleC844FDB1
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/private-function-function/Resource
      aws:asset:path: /Users/prasaddomala/GitRepos/kheriox/youtube/yt-typescript-lambda-cdk/cdk.out/asset.c993b10b13f96d4647db0cf6a9a7019710b34f61600695d887ad66e144f8a93c
      aws:asset:is-bundled: true
      aws:asset:property: Code
  fnprivatefunctionloggroupFAA6666E:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/ts-lambda-private-function-develop
      RetentionInDays: 30
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/fn-private-function-log-group/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/11Qy2rDMBD8lt7Xm8SB3JNCeymluNCrUeStWVuWilZqMUb/HslJCu1pZvYx+6ix3uL2Qf1IpbuxMnzG5T0oPUIOtQurCZfGGYLHT7vimzOs5yKvLAHpOveQjp7D/Oxd/CrZP4EERk3nTuHyombyH+SFnS1l//VTtDpknkD2rRKhIHgskDWeoh4pnJTQza+1rqNB8HWFey8Y10se5frfbe48JWhIXPSaYLXNt/Zs+/W8WyJBccVBNt+7A+72+T2DMFc+2sATYXPFC6hrdxs6AQAA
    Metadata:
      aws:cdk:path: ts-lambda-stack-develop/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

